<a href="https://colab.research.google.com/github/25WH1A0524/NASSCOM-LAB/blob/main/numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
arr1 = np.arange(100, 10, 200)
print("Array using arange:", arr1)

arr2 = np.linspace(10, 111, 51)
print("Array using linspace:", arr2)

arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)
print("Flattened version:", arr3.flatten())

data = np.array([[15, 80, 19], [20, 24, 26]])
print("Original Data:\n", data)

print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))

print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))

a = np.array([13, 21, 73, 22, 19])
print("Original Array:", a)

sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 33)
print("Indices where value > 33:", idx)
print("Values > 33:", a[idx])

A = np.array([[10, 20], [30, 40]])
B = np.array([100, 200])

print("Matrix A:\n", A)
print("Vector B:", B)

C = A + B
print("Broadcasted Addition Result:\n", C)

nums = np.array([10, 20, 30, 40, 50])
mask = nums > 30
print("Mask (nums > 30):", mask)

filtered = nums[mask]
print("Filtered values:", filtered)
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)

arr_orig = np.array([10, 20, 30])
arr_view = arr_orig[:]
arr_view[0] = 99
print("Original After View Change:", arr_orig)

arr_copy = arr_orig.copy()
arr_copy[0] = 66
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)

x = np.array([10, 20, 30])
y = np.array([40, 50, 60])
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)

h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)

rand_ints = np.random.randint(0, 100, size=(5, 5))
print("Random Integers:\n", rand_ints)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)

choices = np.random.choice([1, 2, 5, 9], size=5)
print("Random Choices:", choices)
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())

arr = np.array([100, 200, 300, 400, 500, 600])
print("Original 1D Array:", arr)
print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])


print("Slice from index 1 to 4:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])

matrix = np.array([[11, 12, 13],
                   [14, 15, 16],
                   [17, 18, 19]])

print("Original Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:\n", matrix[:2, :2])

arr = np.array([5, 10, 15, 20, 25, 30])
mask = arr > 10
print("Boolean Mask:", mask)
print("Values greater than 15:", arr[mask])
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])












Array using arange: []
Array using linspace: [ 10.    12.02  14.04  16.06  18.08  20.1   22.12  24.14  26.16  28.18
  30.2   32.22  34.24  36.26  38.28  40.3   42.32  44.34  46.36  48.38
  50.4   52.42  54.44  56.46  58.48  60.5   62.52  64.54  66.56  68.58
  70.6   72.62  74.64  76.66  78.68  80.7   82.72  84.74  86.76  88.78
  90.8   92.82  94.84  96.86  98.88 100.9  102.92 104.94 106.96 108.98
 111.  ]
Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]
Original Data:
 [[15 80 19]
 [20 24 26]]
Sum of all elements: 184
Column-wise sum: [ 35 104  45]
Row-wise mean: [38.         23.33333333]
Max value: 80
Index of max value (flattened): 1
Min value: 15
Standard Deviation: 22.343281366491855
Original Array: [13 21 73 22 19]
Sorted Array: [13 19 21 22 73]
Indices where value > 33: (array([2]),)
Values > 33: [73]
Matrix A:
 [[10 20]
 [30 40]]
Vector B: [100 200]
Broadcasted Addition Result:
 [[110 220]
 [130 240]]
Mask (nums > 30): [False False False 